@startuml

skinparam classAttributeIconSize 0

class Customer{
    +customerName: String
    +customerAddress: String
    +phoneNumber: int

    -putOutBins():void
    -loginToAccount():void

}

class CustomerAccount{
    -userName: String
    -userPassword: String

    -makePayment():void
    -checkBinSchedule():void
    
}

abstract class Bins{
    -binNumber:int
    -binType: String
}

class Brown{
    
}
class Green{

}

class Black{

}


class Drivers{
    +driverName: String
    -driverId: String

    -collectBin(): void
    -checkBinType():void
}

Customer "1 "--|> CustomerAccount 
Customer - Bins : takeOutBin
Bins<|-[#blue]- "1" Brown
Bins<|-[#blue]- "1 " Green 
Bins<|-[#blue]- "1  " Black
Bins"1..2" ---* Drivers

@enduml