@startuml Waste Management Company

left to right direction
actor Consumer as c

package Services {
	usecase centre as "
			Normal: 
			Dispose of Waste at Recycling Centre
			==
			Error: 
			Plant is Closed"
	
	usecase bins as "
			Normal:
			Put out Black/Brown/Green Bins
			==
			Error:
			Wrong waste in bin"
	
	usecase skip as "
			Normal:
			Hire Skip
			==
			Error:
			User damages skip"
}

c --> centre
c --> bins
c --> skip

@enduml
