@startuml Waste Management Company

left to right direction
actor Consumer as c

package Employee {
	actor Driver as d
	actor Admin as a
}

package Services {
	usecase "Dispose of Waste at Recycling Centre" as UC1
	usecase "Black/Brown/Green Bins" as UC2
	usecase "Skip Hire" as UC3
}

package Internal {
	usecase "Transport Waste between Centres" as UC4
}

package Administration {
	usecase "Truck Scheduling" as UC5
	usecase "Create Bin Numbers" as UC6
	usecase "Manage waste inventory" as UC7
}

c --> UC1
c --> UC2
d --> UC2
c --> UC3
d --> UC3

d--> UC4

a --> UC5
d --> UC5
a --> UC6
a --> UC7

@enduml
