@startuml Waste Management Company

left to right direction
actor Consumer as c

package "Waste Management Centre" {
	package Employee {
		actor Driver as d
		actor Admin as a
	}

	package Services {
		usecase centre as "
				== Normal
				<color:#228B22>Dispose of Waste at Recycling Centre
				==
				== Error
				<color:#FF0000>Plant is Closed"
		
		usecase bins as "
				== Normal
				<color:#228B22>Put out Black/Brown/Green Bins
				==
				== Error
				<color:#FF0000>Wrong waste in bin"
		
		usecase skip as "
				== Normal
				<color:#228B22>Hire Skip
				==
				== Error
				<color:#FF0000>User damages skip"
	}

	package Internal {
		usecase transport as "
				== Normal
				<color:#228B22>Transport Waste for Disposal
				== Error
				<color:#FF0000>Truck breaks down"

		usecase dropoff as "
				== Normal
				<color:#228B22>Drop off waste
				== Error
				<color:#FF0000>Drops off wrong waste"
	}

	package Administration {

		usecase truckmanage as "
				== Normal
				<color:#228B22>Schedule Trucks
				==
				== Error
				<color:#FF0000>Driver missing or starts late"

		usecase customermanage as "
				== Normal
				<color:#228B22>Follow up on Customer Complaints
				==
				== Error
				<color:#FF0000>Customer does not want to pay"

		usecase binmanage as "
				== Normal
				<color:#228B22>Keep track of bin locations
				==
				== Error
				<color:#FF0000>Bins are damaged"
	}
}

c --> centre
c --> bins
c --> skip

bins --> d
skip --> d

d --> transport
d --> dropoff

dropoff --> a

a --> truckmanage
a --> customermanage
a --> binmanage

customermanage -> c
truckmanage -> d
binmanage -> customermanage

centre --> a
skip --> a


@enduml
