@startuml

skinparam classAttributeIconSize 0

abstract class Employee
{
    +employeeName: String
    +employeeID: int
    +wage: int

    -collectWage(): void
}

class Admin {

	-customers: CustomerAccount[]
    -employees: Employee[]
	-trucks: BinTruck[]
	-bins: WasteContainer[]

	-interactWithCustomers(): void
    -billCustomer(int amount): void
	-processPayroll(): void
	-scheduleTrucks(): void
	-takeInventoryOfBins(): void
}

class Driver
{
    +truck: BinTruck
    +route: Route

    -transportWaste(): void
    -disposeOfWaste(): void
    +modifyRoute(Route route): void
}

class WasteCollector
{
    +truck: BinTruck

    -collectBin(): void
    -collectSkip(): void
}

class BinTruck
{
    +bins: Bin[]
    +driver: Driver
}

class Waste
{
    +wasteType: String 
    +weight: int
}

class Skip
{
    +size: int
    +weight: int
}

abstract class WasteContainer
{
    +containerID: int
    +waste: Waste[]
    +capacity: int
}

class Customer
{
    +customerName: String
    +customerAddress: String
    +phoneNumber: int

    -putOutBins():void
    -loginToAccount():void
}

class CustomerAccount
{
    +userName: String
    -userPassword: String

    -makePayment():void
    -checkBinSchedule():void
    
}

class Bin
{
    +binType: String
    +owner: Customer
}

class Route
{
    +startLocation: String
    +endLocation: String
    +stops: String[]
}

Employee<|-[#blue]-Driver
Employee<|-[#blue]-WasteCollector
Employee<|-[#blue]-Admin

WasteContainer<|-[#blue]-Skip
WasteContainer<|-[#blue]-Bin

Customer o-- CustomerAccount

WasteCollector .[#blue]. Driver
Driver -- BinTruck
Admin -- BinTruck
Driver o-- WasteContainer
Customer o-- Bin
Admin o-- CustomerAccount
Admin -- Customer
WasteContainer .[#blue]up. Waste
Driver .[#blue]up. Route

@enduml