@startuml
(*) --> "Bin with Reference No. left out on Collection Day"

if "Waste Truck Authorizes Ref No. on Bin is paid for" then
    -->[Payment Confirmed] "Waste Collected"
    --> "Reference No. checked off route list"
    --> "Waste Truck continues on route"
else
    -->[Payment for Waste Collection not Paid] "Waste Truck continues on route"
Endif
--> "Waste Truck finished Bin Collection on Set Route"
--> [Waste Truck Returns to Waste Plant for Disposal] (*)
@enduml